DROP DATABASE IF EXISTS account;

CREATE DATABASE account;

GRANT ALL PRIVILEGES ON DATABASE account TO postgres;

CREATE SCHEMA IF NOT EXISTS app;

CREATE TABLE app.account (
	account_id VARCHAR(255) PRIMARY KEY,
	name TEXT NOT NULL,
	email TEXT NOT NULL,
	password TEXT NOT NULL,
	cpf TEXT NOT NULL,
	car_plate TEXT null,
	is_passenger BOOLEAN NOT NULL DEFAULT false,
	is_driver BOOLEAN NOT NULL DEFAULT false,
	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);