services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .